/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package serverd;

import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author jir
 */
public class download extends javax.swing.JFrame {
     public List<String> list;
     public static String ip="",port="";

    /**
     * Creates new form download
     */
    public download() {
        initComponents();
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jButton1.setText("Image");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setMaximumSize(new java.awt.Dimension(70, 50));
        jButton1.setOpaque(false);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setText("Video");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setMaximumSize(new java.awt.Dimension(70, 50));
        jButton2.setOpaque(false);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setText("Pdf");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setMaximumSize(new java.awt.Dimension(70, 50));
        jButton3.setOpaque(false);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton4.setText("Rar");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setMaximumSize(new java.awt.Dimension(70, 50));
        jButton4.setOpaque(false);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton6.setText("PPT");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setMaximumSize(new java.awt.Dimension(70, 50));
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);

        jButton5.setText("World");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setMaximumSize(new java.awt.Dimension(70, 50));
        jButton5.setOpaque(false);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        jButton7.setText("Audio");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setMaximumSize(new java.awt.Dimension(70, 50));
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton7);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] string={"bilgisayar","yazılım","elektrik","makine","çevre"};

            public int getSize() { return string.length; }
            public String getElementAt(int i) { return string[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jButton8.setText("Download");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Close");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel1.setText("Lütfen seçim yaptıktan sonra indirme yapınız");

        jLabel2.setText("seçilen :");

        jLabel3.setText("...");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton8)
                                .addGap(309, 309, 309))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jLabel1)
                        .addGap(0, 213, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel4)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9)
                        .addGap(15, 15, 15)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addGap(85, 85, 85)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          Clientt cl=new Clientt(ip,port);
         try {
             listeler= cl.startClient(2,"upload",null);
         } catch (IOException ex) {
             Logger.getLogger(download.class.getName()).log(Level.SEVERE, null, ex);
         }
       dsy_nm=2;
       int sayi=0;
        sayi=listeler.size();
        string1=new String[sayi];
        
         for(int k=0;k<sayi;k++){
             if(!listeler.get(k).equals(null)){
                 string1[k]=listeler.get(k);
                
             }
           
       }
       jList1.setModel(new javax.swing.AbstractListModel<String>() {
            public int getSize() { return string1.length; }
            public String getElementAt(int i) { return string1[i]; }
        });
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  Clientt cl=new Clientt(ip,port);
         try {
             listeler= cl.startClient(3,"upload",null);
         } catch (IOException ex) {
             Logger.getLogger(download.class.getName()).log(Level.SEVERE, null, ex);
         }
       dsy_nm=3;
       int sayi=0;
        sayi=listeler.size();
        string1=new String[sayi];
        
         for(int k=0;k<sayi;k++){
             if(!listeler.get(k).equals(null)){
                 string1[k]=listeler.get(k);
                
             }
           
       }
       jList1.setModel(new javax.swing.AbstractListModel<String>() {
            public int getSize() { return string1.length; }
            public String getElementAt(int i) { return string1[i]; }
        });       
    }//GEN-LAST:event_jButton3ActionPerformed
    public List<String> listeler;
    String[] string1;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Clientt cl=new Clientt(ip,port);
         try {
             listeler= cl.startClient(1,"upload",null);
         } catch (IOException ex) {
             Logger.getLogger(download.class.getName()).log(Level.SEVERE, null, ex);
         }
       dsy_nm=1;
       int sayi=0;
        sayi=listeler.size();
        string1=new String[sayi];
        
         for(int k=0;k<sayi;k++){
             if(!listeler.get(k).equals(null)){
                 string1[k]=listeler.get(k);
                
             }
           
       }
       jList1.setModel(new javax.swing.AbstractListModel<String>() {
            public int getSize() { return string1.length; }
            public String getElementAt(int i) { return string1[i]; }
        });
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
          Clientt cl=new Clientt(ip,port);
         try {
             listeler= cl.startClient(4,"upload",null);
         } catch (IOException ex) {
             Logger.getLogger(download.class.getName()).log(Level.SEVERE, null, ex);
         }
       dsy_nm=4;
       int sayi=0;
        sayi=listeler.size();
        string1=new String[sayi];
        
         for(int k=0;k<sayi;k++){
             if(!listeler.get(k).equals(null)){
                 string1[k]=listeler.get(k);
                
             }
           
       }
       jList1.setModel(new javax.swing.AbstractListModel<String>() {
            public int getSize() { return string1.length; }
            public String getElementAt(int i) { return string1[i]; }
        });
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
          Clientt cl=new Clientt(ip,port);
         try {
             listeler= cl.startClient(5,"upload",null);
         } catch (IOException ex) {
             Logger.getLogger(download.class.getName()).log(Level.SEVERE, null, ex);
         }
       dsy_nm=5;
       int sayi=0;
        sayi=listeler.size();
        string1=new String[sayi];
        
         for(int k=0;k<sayi;k++){
             if(!listeler.get(k).equals(null)){
                 string1[k]=listeler.get(k);
                
             }
           
       }
       jList1.setModel(new javax.swing.AbstractListModel<String>() {
            public int getSize() { return string1.length; }
            public String getElementAt(int i) { return string1[i]; }
        });
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         Clientt cl=new Clientt(ip,port);
         try {
             listeler= cl.startClient(6,"upload",null);
         } catch (IOException ex) {
             Logger.getLogger(download.class.getName()).log(Level.SEVERE, null, ex);
         }
       dsy_nm=6;
       int sayi=0;
        sayi=listeler.size();
        string1=new String[sayi];
        
         for(int k=0;k<sayi;k++){
             if(!listeler.get(k).equals(null)){
                 string1[k]=listeler.get(k);
                
             }
           
       }
       jList1.setModel(new javax.swing.AbstractListModel<String>() {
            public int getSize() { return string1.length; }
            public String getElementAt(int i) { return string1[i]; }
        });
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       Clientt cl=new Clientt(ip,port);
         try {
             listeler= cl.startClient(7,"upload",null);
         } catch (IOException ex) {
             Logger.getLogger(download.class.getName()).log(Level.SEVERE, null, ex);
         }
       dsy_nm=7;
       int sayi=0;
        sayi=listeler.size();
        string1=new String[sayi];
        
         for(int k=0;k<sayi;k++){
             if(!listeler.get(k).equals(null)){
                 string1[k]=listeler.get(k);
                
             }
           
       }
       jList1.setModel(new javax.swing.AbstractListModel<String>() {
            public int getSize() { return string1.length; }
            public String getElementAt(int i) { return string1[i]; }
        });
         
    }//GEN-LAST:event_jButton7ActionPerformed
String selection;
     int dsy_nm=0;
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        selection= jList1.getSelectedValue(); 
        jLabel3.setText(selection);
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        String file_path=f.getAbsolutePath();
        Clientt cl=new Clientt(ip,port);
         try {
             cl.startClient(dsy_nm, selection,file_path);
         } catch (IOException ex) {
             Logger.getLogger(download.class.getName()).log(Level.SEVERE, null, ex);
         }
     
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
    
         connect c=new connect();
        c.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton9ActionPerformed


    public static void main(String args[]) {
        ip=args[0];
        port=args[1];
      java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new download().setVisible(true);
            }
        });
       
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
